version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rating-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/thermondo_db
      - SPRING_DATASOURCE_USERNAME=atuin
      - SPRING_DATASOURCE_PASSWORD=at_pass_wd
    depends_on:
      - postgres
    restart: always
    networks:
      - app-db-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=thermondo_db
      - POSTGRES_USER=atuin
      - POSTGRES_PASSWORD=at_pass_wd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-db-network

networks:
  app-db-network:
    driver: bridge

volumes:
  postgres_data:
