version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=thermondo_db
      - POSTGRES_USER=atuin
      - POSTGRES_PASSWORD=at_pass_wd
    restart: always
